#include "audio_lsbto_picture.h"                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                        
//--------------------声音隐写到图片--------------------------//                                                                                                                                                                                                                                                                                                                        
// 读取音频文件并返回二进制数据                                                                                                                                                                                                                                                                                                                                                         
std::string readAudioFile(const std::string& audioPath, SF_INFO& sfinfo)                                                                                                                                                                                                                                                                                                                
{                                                                                                                                                                                                                                                                                                                                                                                       
    SNDFILE* sndfile = sf_open(audioPath.c_str(), SFM_READ, &sfinfo);                                                                                                                                                                                                                                                                                                                   
    if (!sndfile)                                                                                                                                                                                                                                                                                                                                                                       
    {                                                                                                                                                                                                                                                                                                                                                                                   
        std::cerr << "无法打开音频文件！" << std::endl;                                                                                                                                                                                                                                                                                                                                 
        return "";                                                                                                                                                                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                        
    std::vector<short> audioData(sfinfo.frames * sfinfo.channels);                                                                                                                                                                                                                                                                                                                      
    sf_read_short(sndfile, audioData.data(), sfinfo.frames * sfinfo.channels);                                                                                                                                                                                                                                                                                                          
    sf_close(sndfile);                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                        
    std::string binaryData;                                                                                                                                                                                                                                                                                                                                                             
    for (short sample : audioData) 
    {                                                                                                                                                                                                                                                                                                                                                    
        for (int i = 15; i >= 0; --i) 
        {                                                                                                                                                                                                                                                                                                                                                 
            binaryData += ((sample >> i) & 1) ? '1' : '0';                                                                                                                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return binaryData;                                                                                                                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
// LSB 隐写术：将音频二进制数据嵌入到图片中                                                                                                                                                                                                                                                                                                                                             
cv::Mat lsbSteganography(const cv::Mat& image, const std::string& audioBinary)                                                                                                                                                                                                                                                                                                          
{                                                                                                                                                                                                                                                                                                                                                                                       
    cv::Mat stegoImage = image.clone();                                                                                                                                                                                                                                                                                                                                                 
    size_t audioIndex = 0;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                        
    for (int y = 0; y < stegoImage.rows; ++y) 
    {                                                                                                                                                                                                                                                                                                                                         
        for (int x = 0; x < stegoImage.cols; ++x) 
        {                                                                                                                                                                                                                                                                                                                                     
            cv::Vec3b& pixel = stegoImage.at<cv::Vec3b>(y, x);                                                                                                                                                                                                                                                                                                                          
            for (int c = 0; c < 3; ++c) 
            {                                                                                                                                                                                                                                                                                                                                               
                if (audioIndex < audioBinary.length()) 
                {                                                                                                                                                                                                                                                                                                                                
                    // 清除最低有效位                                                                                                                                                                                                                                                                                                                                                   
                    pixel[c] &= 0xFE;                                                                                                                                                                                                                                                                                                                                                   
                    // 嵌入音频数据的一位                                                                                                                                                                                                                                                                                                                                               
                    pixel[c] |= (audioBinary[audioIndex] - '0');                                                                                                                                                                                                                                                                                                                        
                    ++audioIndex;                                                                                                                                                                                                                                                                                                                                                       
                }                                                                                                                                                                                                                                                                                                                                                                       
            }                                                                                                                                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return stegoImage;                                                                                                                                                                                                                                                                                                                                                                  
}                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
// 从隐写图片中提取音频二进制数据                                                                                                                                                                                                                                                                                                                                                       
std::string extractAudioBinary(const cv::Mat& stegoImage, int audioLength)                                                                                                                                                                                                                                                                                                              
{                                                                                                                                                                                                                                                                                                                                                                                       
    std::string audioBinary;                                                                                                                                                                                                                                                                                                                                                            
    int extractedBits = 0;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                        
    for (int y = 0; y < stegoImage.rows; ++y) 
    {                                                                                                                                                                                                                                                                                                                                         
        for (int x = 0; x < stegoImage.cols; ++x) 
        {                                                                                                                                                                                                                                                                                                                                     
            cv::Vec3b pixel = stegoImage.at<cv::Vec3b>(y, x);                                                                                                                                                                                                                                                                                                                           
            for (int c = 0; c < 3; ++c) 
            {                                                                                                                                                                                                                                                                                                                                               
                if (extractedBits < audioLength) 
                {                                                                                                                                                                                                                                                                                                                                      
                    audioBinary += (pixel[c] & 1) ? '1' : '0';                                                                                                                                                                                                                                                                                                                          
                    ++extractedBits;                                                                                                                                                                                                                                                                                                                                                    
                }                                                                                                                                                                                                                                                                                                                                                                       
            }                                                                                                                                                                                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return audioBinary;                                                                                                                                                                                                                                                                                                                                                                 
}                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
// 将二进制数据保存为音频文件                                                                                                                                                                                                                                                                                                                                                           
bool saveAudioFile(const std::string& audioBinary, const std::string& outputPath, SF_INFO sfinfo)                                                                                                                                                                                                                                                                                       
{                                                                                                                                                                                                                                                                                                                                                                                       
    SNDFILE* sndfile = sf_open(outputPath.c_str(), SFM_WRITE, &sfinfo);                                                                                                                                                                                                                                                                                                                 
    if (!sndfile) 
    {                                                                                                                                                                                                                                                                                                                                                                     
        std::cerr << "无法打开输出音频文件！" << std::endl;                                                                                                                                                                                                                                                                                                                             
        return false;                                                                                                                                                                                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                        
    std::vector<short> audioData;                                                                                                                                                                                                                                                                                                                                                       
    for (size_t i = 0; i < audioBinary.length(); i += 16) 
    {                                                                                                                                                                                                                                                                                                                             
        short sample = 0;                                                                                                                                                                                                                                                                                                                                                               
        for (int j = 0; j < 16; ++j) 
        {                                                                                                                                                                                                                                                                                                                                                  
            sample |= ((audioBinary[i + j] - '0') << (15 - j));                                                                                                                                                                                                                                                                                                                         
        }                                                                                                                                                                                                                                                                                                                                                                               
        audioData.push_back(sample);                                                                                                                                                                                                                                                                                                                                                    
    } 
     // 检查写入操作是否成功
    int writeResult = sf_write_short(sndfile, audioData.data(), audioData.size());
    if (writeResult != static_cast<int>(audioData.size())) 
    {
        std::cerr << "音频数据写入失败！" << std::endl;
        sf_close(sndfile);
        return false;  // 写入失败，返回false
    }                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                        
   // sf_write_short(sndfile, audioData.data(), audioData.size());                                                                                                                                                                                                                                                                                                                        
    sf_close(sndfile);
     return true;  // 所有操作成功，返回true                                                                                                                                                                                                                                                                                                                                                                  
} 