#include"common.h"                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                        
std::string intToBinary(int num)                                                                                                                                                                                                                                                                                                                                                        
{                                                                                                                                                                                                                                                                                                                                                                                       
    std::string binary = "";                                                                                                                                                                                                                                                                                                                                                            
    for (int i = 7; i >= 0; --i)                                                                                                                                                                                                                                                                                                                                                        
    {                                                                                                                                                                                                                                                                                                                                                                                   
        binary += ((num >> i) & 1) ? '1' : '0';                                                                                                                                                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return binary;                                                                                                                                                                                                                                                                                                                                                                      
}                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
int binaryToInt(const std::string& binary)                                                                                                                                                                                                                                                                                                                                              
{                                                                                                                                                                                                                                                                                                                                                                                       
    int num = 0;                                                                                                                                                                                                                                                                                                                                                                        
    for (int i = 0; i < 8; ++i)                                                                                                                                                                                                                                                                                                                                                         
    {                                                                                                                                                                                                                                                                                                                                                                                   
        if (binary[i] == '1')                                                                                                                                                                                                                                                                                                                                                           
        {                                                                                                                                                                                                                                                                                                                                                                               
            num |= (1 << (7 - i));                                                                                                                                                                                                                                                                                                                                                      
        }                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return num;                                                                                                                                                                                                                                                                                                                                                                         
}                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                        
std::string charToBinary(char c)                                                                                                                                                                                                                                                                                                                                                        
{                                                                                                                                                                                                                                                                                                                                                                                       
    std::string binary = "";                                                                                                                                                                                                                                                                                                                                                            
    for (int i = 7; i >= 0; --i)                                                                                                                                                                                                                                                                                                                                                        
    {                                                                                                                                                                                                                                                                                                                                                                                   
        binary += ((c >> i) & 1) ? '1' : '0';                                                                                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return binary;                                                                                                                                                                                                                                                                                                                                                                      
}                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
// 2. Binary to character conversion                                                                                                                                                                                                                                                                                                                                                    
char binaryToChar(const std::string& binary)                                                                                                                                                                                                                                                                                                                                            
{                                                                                                                                                                                                                                                                                                                                                                                       
    char c = 0;                                                                                                                                                                                                                                                                                                                                                                         
    for (int i = 0; i < 8; ++i)                                                                                                                                                                                                                                                                                                                                                         
    {                                                                                                                                                                                                                                                                                                                                                                                   
        if (binary[i] == '1')                                                                                                                                                                                                                                                                                                                                                           
        {                                                                                                                                                                                                                                                                                                                                                                               
            c |= (1 << (7 - i));                                                                                                                                                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return c;                                                                                                                                                                                                                                                                                                                                                                           
}                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
// *** Message Handling ***                                                                                                                                                                                                                                                                                                                                                             
std::string getMessageFromTerminal()                                                                                                                                                                                                                                                                                                                                                    
{                                                                                                                                                                                                                                                                                                                                                                                       
    std::string message ="";                                                                                                                                                                                                                                                                                                                                                            
    std::cout << "Enter your message less than 4096 Byte(press Enter to finish):" << std::endl;                                                                                                                                                                                                                                                                                                            
    getline(std::cin, message);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    return message;                                                                                                                                                                                                                                                                                                                                                                    
} 
                                                                                                                                                                                                                                                                                                                                                                                      
// Function to read message from a text file                                                                                                                                                                                                                                                                                                                                            
std::string readMessageFromFile(const std::string& filePath)                                                                                                                                                                                                                                                                                                                            
{                                                                                                                                                                                                                                                                                                                                                                                       
    std::ifstream inputFile(filePath);                                                                                                                                                                                                                                                                                                                                                  
    std::string message = "";                                                                                                                                                                                                                                                                                                                                                           
    std::string line;                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                        
    if (inputFile.is_open())                                                                                                                                                                                                                                                                                                                                                            
    {                                                                                                                                                                                                                                                                                                                                                                                   
        while (getline(inputFile, line))                                                                                                                                                                                                                                                                                                                                                
        {                                                                                                                                                                                                                                                                                                                                                                               
            message += line + "\n";                                                                                                                                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                                                                                                                               
        inputFile.close();                                                                                                                                                                                                                                                                                                                                                              
        //message += END_DELIMITER;  // Append the end delimiter                                                                                                                                                                                                                                                                                                                          
    }                                                                                                                                                                                                                                                                                                                                                                                   
    else                                                                                                                                                                                                                                                                                                                                                                                
    {                                                                                                                                                                                                                                                                                                                                                                                   
        std::cerr << "Error: Could not open file for reading: " << filePath << std::endl;                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                   
    return message;                                                                                                                                                                                                                                                                                                                                                                     
} 

// 将图像的二进制数据转换为十六进制字符串并保存到txt文件
void saveBinaryDataAsHexTxt(const cv::Mat& image, const std::string& filename)
{
    std::ofstream file(filename);
    if (file.is_open())
    {
        for (size_t i = 0; i < image.total() * image.elemSize(); ++i)
        {
            file << std::setw(2) << std::setfill('0') << std::hex << (int)(unsigned char)image.data[i] << " ";
            if ((i + 1) % 16 == 0)
            {
                file << std::endl;
            }
        }
         file.close();
    }
    else
    {
        std::cerr << filename << "is wrong" << std::endl;
    }
}

// Function to convert input to hexadecimal and save it to a file
bool convertAndSaveToFile(const std::string& input, const std::string& filePath) 
{
    std::stringstream hexStream;
    hexStream << std::hex << std::uppercase << std::setfill('0');

    for (char c : input) 
    {
        hexStream << std::setw(2) << static_cast<int>(static_cast<unsigned char>(c));
    }

    std::ofstream outputFile(filePath);

    if (!outputFile.is_open()) 
    {
        std::cerr << "Error opening file for writing: " << filePath << std::endl;
        return false;
    }

    outputFile << hexStream.str();
    outputFile.close();

    std::cout << "Hex representation saved to: " << filePath << std::endl;
    return true;
}