#ifndef MAIN_H                                                                                                                                                                                                                                                              
#define MAIN_H                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                            
#include <iostream>                                                                                                                                                                                                                                                         
#include <fstream>                                                                                                                                                                                                                                                          
#include <string>                                                                                                                                                                                                                                                           
#include <vector>                                                                                                                                                                                                                                                           
#include <opencv2/opencv.hpp>                                                                                                                                                                                                                                               
#include <sndfile.h>                                                                                                                                                                                                                                                        
#include"common.h"                                                                                                                                                                                                                                                          
#include "msg_lsbto_picture.h"                                                                                                                                                                                                                                              
#include "text_lsbto_picture.h"                                                                                                                                                                                                                                             
#include "pic_lsbto_picture.h"                                                                                                                                                                                                                                              
#include "audio_lsbto_picture.h"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   


// 宏定义原始图像路径
//#define ORIGINAL_CARRIER_IMAGE_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/CarrierPic.bmp"
//#define ORIGINAL_CARRIER_IMAGE_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/2048org.bmp"
#define ORIGINAL_CARRIER_IMAGE_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/1.bmp"
//(1)terminal input message save path 
#define STEGO_IMAGE_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/01_StegoMsgOutPut/MsgStego.bmp"
#define EXTRACTED_PIC_MSG_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/01_StegoMsgOutPut/extracted.txt"
#define INPUT_MSG_HEX_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/01_StegoMsgOutPut/OrgMsg.txt"
#define HEX_ORIGIN_PIC_MSG_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/OringinPicHex.txt"
#define HEX_STEGO_PIC_MSG_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/01_StegoMsgOutPut/stegoPicHex.txt"

//(2)text file LSB save path                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
#define STEGO_TEXT_PIC_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/02_StegoFileOutPut/1stego.bmp"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
#define EXTRPIC_TEXT_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/02_StegoFileOutPut/extracted_message.txt"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
#define SECRET_TEXTMSG_PIS_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/02_StegoFileOutPut/SecretMsg.txt"
#define SECRET_ORG_TEXT_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/02_StegoFileOutPut/OrgTextHex.txt"
#define SECRET_STEGO_PIC_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/02_StegoFileOutPut/stegoPicHex.txt"  

  //(3) picture lsb to picture                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
#define SECRET_PIC_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/03_StegoPicOutPut/SecretPic.png"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
#define STEGO_PIC_PATH "/mnt/d/01_StuFile/05_topic/practice/testfile/03_StegoPicOutPut/stegoPic.bmp"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
#define EXTRACT_PIC_PATH  "/mnt/d/01_StuFile/05_topic/practice/testfile/03_StegoPicOutPut/extracted.png"
#define SECRET_PIC_HEX_PATH  "/mnt/d/01_StuFile/05_topic/practice/testfile/03_StegoPicOutPut/SecretHex.txt"
#define STEGO_PIC_HEX_PATH  "/mnt/d/01_StuFile/05_topic/practice/testfile/03_StegoPicOutPut/stegoHex11.txt"
  
  //(4) audio lsb to picture                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
#define wavPath  "/mnt/d/01_StuFile/05_topic/practice/testfile/04_StegoAudioOutput/SecretAudio.mp3"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
#define extractedWavPath  "/mnt/d/01_StuFile/05_topic/practice/testfile/04_StegoAudioOutput/extracted.wav"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
#define stegoAudioPath    "/mnt/d/01_StuFile/05_topic/practice/testfile/04_StegoAudioOutput/stego.bmp"  
#define OrgWavMsg         "/mnt/d/01_StuFile/05_topic/practice/testfile/04_StegoAudioOutput/OrgWavMsg.txt"
#define stegoPicAuMsg         "/mnt/d/01_StuFile/05_topic/practice/testfile/04_StegoAudioOutput/StegoPicWavMsg.txt"                                                                                                                                                                                                                                                                          

 //(5)video lsb to picture                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
// #define outputImagePath  "/mnt/d/01_StuFile/05_topic/practice/testfile/05_StegoVideoOutput/stegVideo.bmp"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 //#define outputVideoPath  "/mnt/d/01_StuFile/05_topic/practice/testfile/05_StegoVideoOutput/extract_video.avi"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
// #define inputVideoPath   "/mnt/d/01_StuFile/05_topic/practice/testfile/05_StegoVideoOutput/input1.avi" 
// #define inputVideoHexPath   "/mnt/d/01_StuFile/05_topic/practice/testfile/05_StegoVideoOutput/inputVideo.txt"
// #define stegoVideoHexPath   "/mnt/d/01_StuFile/05_topic/practice/testfile/05_StegoVideoOutput/stegoVideoHex.txt"                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                            
int select_embedmessage_type_menu(void);                                                                                                                                                                                                                                     
void process_image(int Secret_type, Mat& image); 

#endif 