#ifndef MSG_LSBTO_PICTURE_H                                                                                                                                                                                                                                                                                              
#define MSG_LSBTO_PICTURE_H                                                                                                                                                                                                                                                                                              
#include "common.h"                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                         
using namespace std;                                                                                                                                                                                                                                                                                                     
using namespace cv;                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
//bool embedMessage(const std::string& inputFilename, const std::string& outputFilename, const std::string& message);                                                                                                                                                                                                      
std::string extractMessage(const std::string& inputFilename);                                                                                                                                                                                                                                                            
bool saveMessageToFile(const std::string& filename, const std::string& message);                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
bool embedMessage(Mat& image, const string& message);                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
#endif 