#ifndef PIC_LSBTO_PICTURE_H                                                                                                                                                                                                                                                                                                                                                             
#define PIC_LSBTO_PICTURE_H                                                                                                                                                                                                                                                                                                                                                             
#include "common.h"                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                        
 
// Function to embed the secret image into the carrier image using LSB
bool embedImage(const cv::Mat& carrier, const cv::Mat& secret, cv::Mat& stegoImage);                                                                                                                                                                                                                                                                                                                                                                                       
// Function to extract the secret image from the stego image
cv::Mat extractImage(const cv::Mat& stegoImage);
bool saveImage(const cv::Mat& image, const std::string& filename);
// Function to load an image
cv::Mat loadImage(const std::string& filename);                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                        
#endif 