#ifndef TEXT_LSBTO_PICTURE_H                                                                                                                                                                                                                                                                                             
#define TEXT_LSBTO_PICTURE_H                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                         
#include <iostream>                                                                                                                                                                                                                                                                                                      
#include <fstream>                                                                                                                                                                                                                                                                                                       
#include <string>                                                                                                                                                                                                                                                                                                        
#include <vector>                                                                                                                                                                                                                                                                                                        
#include <opencv2/opencv.hpp>                                                                                                                                                                                                                                                                                            
#include <sndfile.h>                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
//std::string convertFileToText(const std::string& filePath);                                                                                                                                                                                                                                                            
std::string fileToTextConverter(const std::string& inputFilePath);                                                                                                                                                                                                                                                       
bool lsbImageHider(cv::Mat& inputImage, const std::string& messageToHide);                                                                                                                                                                                                                                               
std::string lsbImageRevealer(const cv::Mat& inputImage);                                                                                                                                                                                                                                                                 
bool saveStringToFile(const std::string& content, const std::string& filePath);                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
#endif 